### PR TITLE
Add an option to disable registration.

### PR DESCRIPTION
**Pull request by mzch**
Add an option to disable registration.

### CODE REVIEW

**Comment by DaneeSkripter** [comment]
Hello @mzch ,
I really appreciate your interest in DaneeCloud, but I have a question:
**If admin disable the registration, no one can login, because there won't be any account.**

**Comment by mzch** [comment]
Of couse, firstly an admin have to set false and register (him|her)self. After that an admin will set true if (he|she) wish.

**Comment by DaneeSkripter** [comment]
> Of couse, firstly an admin have to set false and register (him|her)self. After that an admin will set true if (he|she) wish.
> 
> Oh, thanks to fix typos.

Ok, thank you for explanation. When I will have more features to create a new release, I will merge this pull request.

**Review by DaneeSkripter — COMMENTED** [review]
**Code looks good.**

**Pull request merged**
